### ISSUE TITLE
softwareondemand is not working

### ISSUE THREAD

**Issue by kochd** [kochd/opsi-postgres#5]
According to https://forum.opsi.org/viewtopic.php?f=8&t=7429
There could be a problem when using opsi-postgres with softwareondemand 

 > it says "no products found" when i open https://localhost:4441/swondemand.

Needs to be verified

**Comment by kochd** [comment]
confirmed

it relates to the **filter array that is passed to config_getObjects. 

> [8] [May 27 18:22:09] SQL query: select * from "CONFIG" where ("configId" = 'software-on-demand.*') (Postgres.py|411)

Is valid for mysql. Its not ansi compliant and therefore not valid for postgres.

**Comment by roeltorres** [comment]
Hi dkoch, can we try an equivalent command in postgres. The software on demand is very usefull. This is very interisting. I'll try postgres also but i think we need to find a way to solve it. Lets work together to find solution, the problem is im not so familiar with postgres.

**Comment by kochd** [comment]
That query does not return a set on mysql either. Fell free to investigate the problem if you are familar with python. I will be working on this too but in my spare time which is limited.

**Comment by kochd** [comment]
fixed by 216df63cd5e0036403cc5fc70e19cc959da35130

**Comment by roeltorres** [comment]
Great job kochd, That was quick. Can I just update the 2 files SQLpg.py and Postgres.py  or do I need to go through the entire procedure when I migrate to Postgres database? Thank you so much.

**Comment by kochd** [comment]
Just restart opsiconfd

Am 29.05.2015 um 14:52 schrieb roeltorres:

**Comment by rmtevesjr** [comment]
Hi kochd, Does the fix requires me to upgrade to 4.0.5? Im using OPSI 4.0.4? I hope it's compatible with 4.0.4. I'll just upgrade to 4.0.5 later. Thank you.

**Comment by kochd** [comment]
As far as I remember its also compatible with 404. It's not tested so I don't know
Am 06.06.2015 12:59 schrieb rmtevesjr notifications@github.com:Hi kochd, Does the fix requires me to upgrade to 4.0.5? Im using OPSI 4.0.4? I hope it's compatible with 4.0.4. I'll just upgrade to 4.0.5 later. Thank you.

**Comment by rmtevesjr** [comment]
Hi Kochd, I encountered this error when I implemented the fix. Any idea? Thanks a lot.

Opsi service error: [OperationalError] stack depth limit exceeded HINT: Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.

**Comment by kochd** [comment]
I need more details. When does this happen ?

Am 18.06.2015 um 16:30 schrieb rmtevesjr:

**Comment by rmtevesjr** [comment]
It happened when I login to OPSI Configed. After I type the user name and password it will run the JAVA then it should open the OPSI configed (Web interface) but now the error appear.

**Comment by kochd** [comment]
Not for me. Sorry. But I am using 4.0.5 so i dont know.
How about logs ? Use 'opsiconfd -l8' for useful output

Am 18.06.2015 um 16:37 schrieb rmtevesjr:

**Comment by rmtevesjr** [comment]
Ok, will check the logs. I need to check also the version.. Thanks Kochd.

**Comment by rmtevesjr** [comment]
One more question, What postgres version are you using? Thanks again.

**Comment by kochd** [comment]
9.4.3

Am 18.06.2015 um 16:54 schrieb rmtevesjr:
